# Generated by Django 5.0 on 2024-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Locality', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('Pin', models.PositiveIntegerField()),
                ('State', models.CharField(max_length=50)),
                ('Mobile_No', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Job_City', models.CharField(max_length=50)),
                ('Profile_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
