# Generated by Django 5.0 on 2024-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_resume_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Profile_Image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
