# Generated by Django 5.0 on 2024-01-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_resume_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Profile_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
