# Generated by Django 5.0 on 2024-01-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
