# Generated by Django 5.0 on 2024-01-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='Description',
            field=models.TextField(),
        ),
    ]
