# Generated by Django 5.0 on 2024-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resume_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Serial_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='Profile_Image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
